{
  imports = [
    ./askpass.nix
    ./atuin.nix
    ./avatar.nix
    ./bacon.nix
    ./bat.nix
    ./btop.nix
    ./carapace.nix
    ./cosmic-settings.nix
    ./direnv.nix
    ./eza.nix
    ./fastfetch.nix
    ./firefox.nix
    ./fzf.nix
    ./gtk.nix
    ./git.nix
    ./hermes.nix
    ./home-packages.nix
    ./jujutsu.nix
    ./lazygit.nix
    ./neovim.nix
    ./nushell.nix
    ./quill.nix
    ./ssh.nix
    ./starship.nix
    ./wezterm.nix
    ./yazi.nix
    ./zoxide.nix
  ];
}
